### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jeisonx** [Asteezy24/SupremeRestocks#1]
When i do npm start to start the script, i  have the latest version of node.js and npm installed.
<img width="906" alt="screen shot 2017-07-06 at 9 06 17 pm" src="https://user-images.githubusercontent.com/22186712/27938913-54e0b26a-628f-11e7-99ad-3b33a52cd7ac.png">

npm-debug.log: https://pastebin.com/0cpnEbQJ

**Comment by Asteezy24** [comment]
Yeah right now it only supports slack integration. So unless you put a slack API token into the blank variable on line 16 it wont work. Also supreme's webstore is down for a couple months so I would hold off on testing right now. When it gets closer to the new supreme season you will see more updates on this script. But for right now it is in the very early stages of development

**Comment by Jeisonx** [comment]
Got it.

**Comment by Bleez103** [comment]
@Asteezy24  Can you look into this? The bot joins the slack channel, but  the same error appears above after few minutes of running.
