### ISSUE TITLE
Can you add discord support?

### ISSUE THREAD

**Issue by ghost** [Asteezy24/SupremeRestocks#2]
I'd love for you to add discord support with the proper formatting! :)

**Comment by Asteezy24** [comment]
I'll see what I can do!

**Comment by Bleez103** [comment]
Can you also look into the below error? @Asteezy24 

![image](https://user-images.githubusercontent.com/25425376/30790283-e305b57c-a15f-11e7-80ca-3266fbdf0cdc.png)

**Comment by Asteezy24** [comment]
Everything should be fixed with the new version. Open a new issue if any problems persist!
